import React, { useEffect, useState } from "react";
import DashboardLayout from "../../components/DashboardLayout.jsx";
import apiClient from "../../api/axiosClient.js";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell, CartesianGrid } from "recharts";

const Icon = ({ children, className = "h-5 w-5" }) => (
  <svg viewBox="0 0 24 24" className={className} fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
    {children}
  </svg>
);

const formatLKR = (n) => `Rs. ${Number(n || 0).toLocaleString("en-LK", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

const CROP_COLORS = ["#1C3D20", "#2F7D4F", "#5BA876", "#8FC9A0", "#B7DFC0", "#DDEFE1"];

function StatCard({ icon, label, value, sub, accent = "bg-emerald-50 text-[#1C3D20]" }) {
  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
      <div className="flex items-start justify-between gap-3">
        <div>
          <p className="text-sm font-medium text-slate-500">{label}</p>
          <p className="mt-2 text-2xl font-bold tracking-tight text-slate-900">{value}</p>
          {sub && <p className="mt-1 text-xs text-slate-500">{sub}</p>}
        </div>
        <span className={`grid h-11 w-11 flex-none place-items-center rounded-xl ${accent}`}>{icon}</span>
      </div>
    </div>
  );
}

export default function AdminOverview() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const load = async () => {
    setLoading(true);
    setError("");
    try {
      const { data } = await apiClient.get("/admin/overview");
      setData(data);
    } catch (err) {
      setError(err.response?.data?.message || "Unable to load analytics. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load();
  }, []);

  const statusTotal = data ? data.totals.pendingReview + data.totals.approved + data.totals.rejected : 0;

  return (
    <DashboardLayout
      title="System Overview"
      subtitle="Aggregate performance of every fertilizer recommendation generated by FertiSmart SL."
      actions={
        <button
          type="button"
          onClick={load}
          disabled={loading}
          className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 shadow-sm transition hover:border-emerald-300 hover:bg-emerald-50 disabled:opacity-60"
        >
          <Icon className="h-4 w-4"><path d="M21 12a9 9 0 11-3-6.7M21 4v5h-5" /></Icon>
          {loading ? "Refreshing..." : "Refresh"}
        </button>
      }
    >
      {loading && !data && (
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
          {Array.from({ length: 4 }).map((_, i) => (
            <div key={i} className="h-28 animate-pulse rounded-2xl border border-slate-200 bg-slate-50" />
          ))}
        </div>
      )}

      {!loading && error && (
        <div className="rounded-2xl border border-red-200 bg-red-50 p-6">
          <p className="font-semibold text-red-800">Unable to load analytics</p>
          <p className="mt-1 text-sm text-red-700">{error}</p>
          <button type="button" onClick={load} className="mt-4 rounded-lg bg-red-700 px-4 py-2 text-sm font-semibold text-white hover:bg-red-800">
            Try again
          </button>
        </div>
      )}

      {!loading && !error && data && (
        <div className="space-y-7">
          {/* Top stat cards */}
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
            <StatCard
              label="Total recommendations"
              value={data.totals.recommendations}
              sub="Generated across all farmers"
              icon={<Icon><path d="M9 3h6M10 3v7l-5 9a2 2 0 002 2h10a2 2 0 002-2l-5-9V3" /></Icon>}
            />
            <StatCard
              label="Awaiting review"
              value={data.totals.pendingReview}
              sub={`${data.totals.approved} approved · ${data.totals.rejected} rejected`}
              accent="bg-amber-50 text-amber-700"
              icon={<Icon><rect x="3" y="5" width="18" height="16" rx="2" /><path d="M16 3v4M8 3v4M3 10h18" /></Icon>}
            />
            <StatCard
              label="Total fertilizer cost recommended"
              value={formatLKR(data.cost.totalCostLKR)}
              sub="Sum of all optimized recommendations"
              icon={<Icon><path d="M12 1v22M17 5H9.5a3.5 3.5 0 000 7h5a3.5 3.5 0 010 7H6" /></Icon>}
            />
            <StatCard
              label="Total savings vs conventional"
              value={formatLKR(data.cost.totalSavingsLKR)}
              sub={`Average ${data.cost.avgSavingsPercent.toFixed(1)}% saved per recommendation`}
              accent="bg-emerald-50 text-emerald-700"
              icon={<Icon><path d="M3 17l6-6 4 4 8-8M21 7v6h-6" /></Icon>}
            />
          </div>

          {/* Status breakdown bar */}
          {statusTotal > 0 && (
            <div className="rounded-2xl border border-slate-200 bg-white p-5">
              <p className="text-sm font-semibold text-slate-700">Review status breakdown</p>
              <div className="mt-3 flex h-4 w-full overflow-hidden rounded-full bg-slate-100">
                <div className="bg-amber-400" style={{ width: `${(data.totals.pendingReview / statusTotal) * 100}%` }} />
                <div className="bg-emerald-600" style={{ width: `${(data.totals.approved / statusTotal) * 100}%` }} />
                <div className="bg-red-400" style={{ width: `${(data.totals.rejected / statusTotal) * 100}%` }} />
              </div>
              <div className="mt-3 flex flex-wrap gap-4 text-xs text-slate-600">
                <span className="flex items-center gap-1.5"><span className="h-2.5 w-2.5 rounded-full bg-amber-400" /> Pending ({data.totals.pendingReview})</span>
                <span className="flex items-center gap-1.5"><span className="h-2.5 w-2.5 rounded-full bg-emerald-600" /> Approved ({data.totals.approved})</span>
                <span className="flex items-center gap-1.5"><span className="h-2.5 w-2.5 rounded-full bg-red-400" /> Rejected ({data.totals.rejected})</span>
              </div>
            </div>
          )}

          {/* Charts */}
          <div className="grid grid-cols-1 gap-5 lg:grid-cols-2">
            <div className="rounded-2xl border border-slate-200 bg-white p-5">
              <p className="text-sm font-semibold text-slate-700">Recommendations by crop</p>
              <div className="mt-3 h-64 w-full">
                {data.byCrop.length > 0 ? (
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={data.byCrop} margin={{ top: 4, right: 8, left: -16, bottom: 4 }}>
                      <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#EEF2F0" />
                      <XAxis dataKey="name" tick={{ fontSize: 10 }} interval={0} angle={-30} textAnchor="end" height={60} />
                      <YAxis allowDecimals={false} tick={{ fontSize: 11 }} />
                      <Tooltip contentStyle={{ fontSize: 12, borderRadius: 8 }} />
                      <Bar dataKey="count" radius={[6, 6, 0, 0]}>
                        {data.byCrop.map((_, i) => <Cell key={i} fill={CROP_COLORS[i % CROP_COLORS.length]} />)}
                      </Bar>
                    </BarChart>
                  </ResponsiveContainer>
                ) : (
                  <p className="flex h-full items-center justify-center text-sm text-slate-400">No data yet</p>
                )}
              </div>
            </div>

            <div className="rounded-2xl border border-slate-200 bg-white p-5">
              <p className="text-sm font-semibold text-slate-700">Recommendations by region</p>
              <div className="mt-3 h-64 w-full">
                {data.byRegion.length > 0 ? (
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={data.byRegion} layout="vertical" margin={{ top: 4, right: 24, left: 8, bottom: 4 }}>
                      <CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#EEF2F0" />
                      <XAxis type="number" allowDecimals={false} tick={{ fontSize: 11 }} />
                      <YAxis type="category" dataKey="name" width={110} tick={{ fontSize: 11 }} />
                      <Tooltip contentStyle={{ fontSize: 12, borderRadius: 8 }} />
                      <Bar dataKey="count" radius={[0, 6, 6, 0]} fill="#1C3D20" barSize={26} />
                    </BarChart>
                  </ResponsiveContainer>
                ) : (
                  <p className="flex h-full items-center justify-center text-sm text-slate-400">No data yet</p>
                )}
              </div>
            </div>
          </div>
        </div>
      )}
    </DashboardLayout>
  );
}
